services:
  add_product_to_order_db:
    image: postgres:14.4-alpine
    container_name: add_product_to_order_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - add_product_to_order_postgres_data:/var/lib/postgres/data
    env_file: .env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
    networks:
      - web_network

  add_product_to_order:
    container_name: add_product_to_order_app
    build: .
    depends_on:
        add_product_to_order_db:
            condition: service_healthy
    command: sh -c "uv run alembic upgrade head && uv run python main.py"
    env_file: .env
    ports:
      - "8001:8001"
    networks:
      - web_network

volumes:
  add_product_to_order_postgres_data:

networks:
  web_network:
    name: web_network
